upstream hswx.front.test {
    server php81:8795;
    keepalive 10240;
}

server {
  server_name hswx.front.test;
  listen 80;

  location / {
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header Host $host;
      proxy_http_version 1.1;
      proxy_set_header Connection "";
      if (!-f $request_filename){
          proxy_pass http://hswx.front.test;
      }
  }
}
