version: "3.2"

#设置网络
networks:
  app-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16

services:

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/log:/var/log/nginx
      - ${WEB_ROOT_PATH}:/var/www
    depends_on:
      - php81
      - mysql
      - redis
    networks:
      app-net:
        ipv4_address: 10.5.0.5

  php74:
    container_name: php74
    build:
      context: ./php-fpm/conf-7.4
    ports:
      - 9074:9000
    volumes:
      - ./php-fpm/conf-7.4/php.ini:/usr/local/etc/php/php.ini
      - ./php-fpm/conf-7.4/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./php-fpm/conf-7.4/php-fpm.d:/usr/local/etc/php-fpm.d
      - ${WEB_ROOT_PATH}:/var/www
    networks:
      app-net:
        ipv4_address: 10.5.0.6
    extra_hosts:
      ad.zl.test: 10.5.0.5
      api.zl.test: 10.5.0.5

  php81:
    container_name: php81
    build:
      context: ./php-fpm/conf-8.1
    ports:
      - 9081:9000
    volumes:
      - ./php-fpm/conf-8.1/php.ini:/usr/local/etc/php/php.ini
      - ./php-fpm/conf-8.1/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./php-fpm/conf-8.1/php-fpm.d:/usr/local/etc/php-fpm.d
      - ${WEB_ROOT_PATH}:/var/www
    networks:
      app-net:
        ipv4_address: 10.5.0.7
    extra_hosts:
      ad.zl.test: 10.5.0.5
      api.zl.test: 10.5.0.5

  php84:
    container_name: php84
    build:
      context: ./php-fpm/conf-8.4
    ports:
      - 9084:9000
    volumes:
      - ./php-fpm/conf-8.4/php.ini:/usr/local/etc/php/php.ini
      - ./php-fpm/conf-8.4/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./php-fpm/conf-8.4/php-fpm.d:/usr/local/etc/php-fpm.d
      - ${WEB_ROOT_PATH}:/var/www
    networks:
      app-net:
        ipv4_address: 10.5.0.20
    extra_hosts:
      ad.zl.test: 10.5.0.5
      api.zl.test: 10.5.0.5

  mysql:
    container_name: mysql
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    command:
      --default-authentication-plugin=mysql_native_password
      --max_allowed_packet=200M
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      app-net:
        ipv4_address: 10.5.0.8

  mongo:
    container_name: mongo
    build:
      context: ./mongo
      args:
        - MONGO_VERSION=${MONGO_VERSION}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ./mongo/data:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    networks:
      app-net:
        ipv4_address: 10.5.0.9

  redis:
    container_name: redis
    build:
      context: ./redis
      args:
        - REDIS_VERSION=${REDIS_VERSION}
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./redis/data:/data
    restart: always
    networks:
      app-net:
        ipv4_address: 10.5.0.10

  redis_cluster_node1:
    container_name: redis_cluster_node1
    build:
      context: ./redis/cluster/node1
      args:
        - REDIS_VERSION=${REDIS_VERSION}
    ports:
      - ${REDIS_CLUSTER_NODE1_PORT}:6379
    volumes:
      - ./redis/cluster/node1/data:/data
    restart: always
    networks:
      app-net:
        ipv4_address: 10.5.0.12

  redis_cluster_node2:
    container_name: redis_cluster_node2
    build:
      context: ./redis/cluster/node2
      args:
        - REDIS_VERSION=${REDIS_VERSION}
    ports:
      - ${REDIS_CLUSTER_NODE2_PORT}:6379
    volumes:
      - ./redis/cluster/node2/data:/data
    restart: always
    networks:
      app-net:
        ipv4_address: 10.5.0.13

  redis_cluster_node3:
    container_name: redis_cluster_node3
    build:
      context: ./redis/cluster/node3
      args:
        - REDIS_VERSION=${REDIS_VERSION}
    ports:
      - ${REDIS_CLUSTER_NODE3_PORT}:6379
    volumes:
      - ./redis/cluster/node3/data:/data
    restart: always
    networks:
      app-net:
        ipv4_address: 10.5.0.14

  redis_cluster_node4:
    container_name: redis_cluster_node4
    build:
      context: ./redis/cluster/node4
      args:
        - REDIS_VERSION=${REDIS_VERSION}
    ports:
      - ${REDIS_CLUSTER_NODE4_PORT}:6379
    volumes:
      - ./redis/cluster/node4/data:/data
    restart: always
    networks:
      app-net:
        ipv4_address: 10.5.0.15

  redis_cluster_node5:
    container_name: redis_cluster_node5
    build:
      context: ./redis/cluster/node5
      args:
        - REDIS_VERSION=${REDIS_VERSION}
    ports:
      - ${REDIS_CLUSTER_NODE5_PORT}:6379
    volumes:
      - ./redis/cluster/node5/data:/datad
    restart: always
    networks:
      app-net:
        ipv4_address: 10.5.0.16

  redis_cluster_node6:
    container_name: redis_cluster_node6
    build:
      context: ./redis/cluster/node6
      args:
        - REDIS_VERSION=${REDIS_VERSION}
    ports:
      - ${REDIS_CLUSTER_NODE6_PORT}:6379
    volumes:
      - ./redis/cluster/node6/data:/data
    restart: always
    networks:
      app-net:
        ipv4_address: 10.5.0.17

  memcached:
    container_name: memcached
    build:
      context: ./memcached
      args:
        - MEMCACHED_VERSION=${MEMCACHED_VERSION}
    ports:
      - ${MEMCACHED_PORT}:11211
    networks:
      app-net:
        ipv4_address: 10.5.0.11